### ISSUE TITLE
Add standard deviation to c_resources_per_pt

### ISSUE THREAD

**Issue by mikix** [smart-on-fhir/cumulus-library-data-metrics#19]
Standard deviation would be a useful statistic to add to `c_resources_per_pt` (in addition to the existing average and max stats)

#### Original report below
~~Standard deviation & median come to mind.~~

**Comment by gotdan** [comment]
Cool, should we change the title of this issue to std deviation - I think that's the only column that's still missing here?

**Comment by mikix** [comment]
Std deviation and also median.

**Comment by gotdan** [comment]
I think we could probably skip median - some quick googling indicates it's pretty inefficient to calculate in sql, and not sure it's high value for this use case anyway...
