### ISSUE TITLE
DocumentReference attachment/url check

### ISSUE THREAD

**Issue by gotdan** [smart-on-fhir/cumulus-library-data-metrics#7]
Currently, the us-core-6 attachment data/url check for DocumentReference [is skipped](https://github.com/smart-on-fhir/cumulus-library-data-metrics/blob/main/data_metrics/us_core_v4/documentreference_mandatory.jinja) since Cumulus strips that element. This makes sense once the data has been loaded, but it's an important check if we plan to process the notes coming from bulk data using NLP. Should we have a flag to enable this, or alternatively, add a "NLP ready" version of the metric that inherits from the US Core metric and adds this check?

**Comment by mikix** [comment]
One piece of this puzzle that would allow analyzing url/data fields en masse (not just local data mode) is https://github.com/smart-on-fhir/cumulus-etl/pull/361
